### ISSUE TITLE
Calling asset::create_asset shows an error “Value cannot be printed”.

### ISSUE THREAD

**Issue by adamdossa** [Zondax/ledger-polymesh#24]
![Screenshot 2021-02-04 at 09 58 31](https://user-images.githubusercontent.com/2633913/106876646-d869ae00-66cf-11eb-9dff-f98772827f51.png)

**Comment by jleni** [comment]
The tx can be expressed as a hexstring:

```
1d042854455354544f4b31323354455354544f4b31323300000000000000000000000000000000000000000000d5023400dd0700000500000012fddc9e2128b3fe571e4e5427addcb87fcaf08493867a68dd6ae44b406b39c7d4c47c57b27929c90cbe4cb38945c57d3840513293a541135f91015d17f4a817
```

And the internal parser is interpreting this as:

```
0 | Asset : Create asset
1 | Name : TESTTOK123
2 | Ticker : TESTTOK123
3 | Total supply : POLYX 0.0
4 | Divisible : False
5 | Asset type : EquityCommon
6 | Identifiers : Value cannot be printed
7 | Funding round : None
```

The problem is that the `identifiers` vector seems empty and we are expecting at least 1 item.
We may need to handle the empty vector and show an empty field instead.

**Comment by adamdossa** [comment]
That makes sense - the extrinsic signature is below:
```
        pub fn create_asset(
            origin,
            name: AssetName,
            ticker: Ticker,
            total_supply: T::Balance,
            divisible: bool,
            asset_type: AssetType,
            identifiers: Vec<AssetIdentifier>,
            funding_round: Option<FundingRoundName>,
        )
 ```
As you say, the `identifiers` vector can be of size 0 (and might be quite often since identifiers can also be updated after the asset is created). This is more generally true when we take in vectors as parameters, it is valid that they are empty usually.

**Comment by jleni** [comment]
Perfect. Yes, the case of empty was not accepted
