### ISSUE TITLE
Ledger device shows "ERROR SHOWING DATA"

### ISSUE THREAD

**Issue by adamdossa** [Zondax/ledger-polymesh#31]
When submitting a `settlement::affirm_instruction` with a single portfolio, the Ledger device shows "ERROR SHOWING DATA" whilst trying to display the transaction.

The data being passed to the ledger to sign is:
`24041802000000000000047c4b2319b2bb91b6685716d17f52e5d2b179b2837272a0d12269b8bbec47b7a600e5013c00dd0700000500000012fddc9e2128b3fe571e4e5427addcb87fcaf08493867a68dd6ae44b406b39c7ad81e455cc6e90afcb59fa70d45dc3a485d231450c2741e384e5a79e4424efa4`

![Image from iOS (1)](https://user-images.githubusercontent.com/2633913/109152442-67179b00-7763-11eb-88bc-c9ff309ff505.jpg)
![Image from iOS (2)](https://user-images.githubusercontent.com/2633913/109152447-6979f500-7763-11eb-85be-a369d6168388.jpg)

Note - this also causes polkadot.js to crash and need a reload.

**Comment by adamdossa** [comment]
FYI - this looks related interpreting the PortfolioKind within the PortfolioId:
```
pub enum PortfolioKind {
    /// The default portfolio of a DID.
    Default,
    /// A user-defined portfolio of a DID.
    User(PortfolioNumber),
}
```

If I use the `User(...)` variant it works, but if I use the `Default` variant it doesn't.

**Comment by jleni** [comment]
I see... mm..

**Comment by jleni** [comment]
when we randomize test cases... we can also sometimes add some fix ones.. I wonder how we never hit the Default case..
I will look at it now.
There are a few fixes in the PR related to sr25519 that I am pushing in 5 mins
and then I move into this

**Comment by jleni** [comment]
related to #33
